FROM cannin/jupyter-keras-tensorflow-tools:tf-1.4.0-py3

# Installing required software
#RUN apt-get update
RUN apt-get install -y openssh-server
RUN apt-get install -y supervisor
RUN apt-get install -y sudo

RUN echo 'root:root' | chpasswd

RUN mkdir /var/run/sshd

# Enabling root login
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

COPY supervisor/*.conf /etc/supervisor/conf.d/

EXPOSE 22

WORKDIR /notebooks

CMD ["/usr/bin/supervisord"]
